#grpc api
grpc:
  server:
    security:
      enabled: false

#mongodb
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: movie_db
      authentication-database: admin
      username: user
      password: user